In [1]:
import numpy as np

In [2]:
a = np.array([
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
columns = a[:, 0:2]
print("\nFirst and Second Columns:\n", columns)


First and Second Columns:
 [[1 2]
 [4 5]
 [7 8]]


In [20]:
# new_row = np.array([[10, 11, 14]])
# print(new_row)
a = np.array([
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ])
a = np.append(a, [[10, 11, 14]], axis=1)
print("\nArray after appending a new row:\n", a)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 1

In [15]:
pos_index_element = a[0, 0]
print("\nElement using positive indexing (a[0,0]):", pos_index_element)


Element using positive indexing (a[0,0]): 1


In [16]:
neg_index_element = a[-1, -1]
print("Element using negative indexing (a[-1,-1]):", neg_index_element)

Element using negative indexing (a[-1,-1]): 14


In [17]:
subset = a[1:3, 1:3]
print("\nSliced subset (rows 1-2 and columns 1-2):\n", subset)


Sliced subset (rows 1-2 and columns 1-2):
 [[5 6]
 [8 9]]


In [19]:
new_column = np.array([[100], [200], [300]])
a_with_new_col = np.insert(a, 1, new_column, axis=1)
print("\nArray after inserting a new column at index 1:\n", a_with_new_col)


Array after inserting a new column at index 1:
 [[  1 100 200 300   2   3]
 [  4 100 200 300   5   6]
 [  7 100 200 300   8   9]
 [ 10 100 200 300  11  14]]
