In [6]:
import numpy as np

In [7]:
list = [1,2,3,4,5]
print(list)

[1, 2, 3, 4, 5]


In [8]:
print("1D array")
a = np.array([1,2,3,4,5])
print(a)

1D array
[1 2 3 4 5]


In [9]:
print("2D array")
b = np.array([[1,2,3,4,5],[1,2,3,4,5]])
print(b)

2D array
[[1 2 3 4 5]
 [1 2 3 4 5]]


In [10]:
print("3D array")
c = np.array([[1,2,3,4,5],
               [1,2,3,4,5],
               [1,2,3,4,5]])
print(c)

3D array
[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]


In [11]:
type(a)

numpy.ndarray

In [12]:
print(a.size)
print(b.size)
print(c.size)

5
10
15


In [13]:
print(a.shape)
print(b.shape)
print(c.shape)

(5,)
(2, 5)
(3, 5)


In [14]:
print(a.dtype)
print(b.dtype)
print(c.dtype)

int64
int64
int64


In [15]:
d = np.array([1,2,3.5,6])
print(d.dtype)

float64


In [17]:
print(c)
c.transpose()


[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]


array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4],
       [5, 5, 5]])