In [1]:
import numpy as np

np.empty((row,col),dtype)

In [2]:
np.empty((3,3),dtype = float)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [3]:
x = np.ones(5)
x

array([1., 1., 1., 1., 1.])

In [4]:
y = np.ones((3,5))
y

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [5]:
z = np.ones((3,5), dtype = int)
z

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

similer to ones , zeroes 

In [6]:
a = np.zeros((2,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

we can add dtype in str and bool

In [9]:
x = np.ones((3,5) , dtype = int)    #if its zeros , that would empty string
x

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [10]:
x = np.ones((3,5), dtype = bool)     # if its zeros all values will be false 
x 

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])