In [1]:
import numpy as np

In [3]:
d = np.arange(10)
e = d[1:5]
e[0]=10
print(e)
print(d)

[10  2  3  4]
[ 0 10  2  3  4  5  6  7  8  9]


np.arange(start,end , step)

In [5]:
a = np.arange(20)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [6]:
a = np.arange(2,20,2)
print(a)

[ 2  4  6  8 10 12 14 16 18]


arr.reshape((rows,cols))

In [7]:
a = a.reshape((3,3))
print(a)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [8]:
b = np.arange(1,100,2)
b = b.reshape(10,5)
print(b)

[[ 1  3  5  7  9]
 [11 13 15 17 19]
 [21 23 25 27 29]
 [31 33 35 37 39]
 [41 43 45 47 49]
 [51 53 55 57 59]
 [61 63 65 67 69]
 [71 73 75 77 79]
 [81 83 85 87 89]
 [91 93 95 97 99]]


In [12]:
b = b.flatten()             #opp of arange

print(b)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]


In [ ]:
a = a.ravel()          #opp of arange
a

flatten() returns a copy of the array, so changes don’t affect the original. ravel() returns a view (if possible), so changes may affect the original.


In [13]:
a = np.array([[1, 2], [3, 4]])

# Using flatten()
flat = a.flatten()
flat[0] = 99
print("After flatten():")
print("Original array:\n", a)  # Unchanged
print("Flattened array:\n", flat)  # Modified

# Using ravel()
ravelled = a.ravel()
ravelled[0] = 99
print("\nAfter ravel():")
print("Original array:\n", a)  # Changed (view)
print("Ravelled array:\n", ravelled)  # Same as original

After flatten():
Original array:
 [[1 2]
 [3 4]]
Flattened array:
 [99  2  3  4]

After ravel():
Original array:
 [[99  2]
 [ 3  4]]
Ravelled array:
 [99  2  3  4]
