In [4]:
import numpy as np

In [5]:
a = np.arange(1,51)
a = a.reshape(10,5)
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]
 [36 37 38 39 40]
 [41 42 43 44 45]
 [46 47 48 49 50]]


In [6]:
a[0]

array([1, 2, 3, 4, 5])

In [7]:
print(a[1,3])

9


In [8]:
a[2:5]          #slicing

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [9]:
a[:,2]          #all the rows of 3rd col

array([ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48])

In [10]:
a[2:5,4]

array([15, 20, 25])

In [11]:
a[:,:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [12]:
a[:,2:5]

array([[ 3,  4,  5],
       [ 8,  9, 10],
       [13, 14, 15],
       [18, 19, 20],
       [23, 24, 25],
       [28, 29, 30],
       [33, 34, 35],
       [38, 39, 40],
       [43, 44, 45],
       [48, 49, 50]])

In [13]:
a[:,2:5].dtype

dtype('int64')