In [1]:
import numpy as np

In [3]:
a = np.arange(0,18).reshape((6,3))
b = np.arange(20,38).reshape((6,3))
print(a,"\n\n" ,b)


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]] 

 [[20 21 22]
 [23 24 25]
 [26 27 28]
 [29 30 31]
 [32 33 34]
 [35 36 37]]


In [4]:
# a+b

#or 

np.add(a,b)

array([[20, 22, 24],
       [26, 28, 30],
       [32, 34, 36],
       [38, 40, 42],
       [44, 46, 48],
       [50, 52, 54]])

In [5]:
np.subtract(b,a)

array([[20, 20, 20],
       [20, 20, 20],
       [20, 20, 20],
       [20, 20, 20],
       [20, 20, 20],
       [20, 20, 20]])

In [6]:
np.multiply(a,b)

array([[  0,  21,  44],
       [ 69,  96, 125],
       [156, 189, 224],
       [261, 300, 341],
       [384, 429, 476],
       [525, 576, 629]])

In [8]:
np.divide(b,a)

C:\Users\sarvan\AppData\Local\Temp\ipykernel_16140\3421666983.py:1: RuntimeWarning: divide by zero encountered in divide
  np.divide(b,a)


array([[        inf, 21.        , 11.        ],
       [ 7.66666667,  6.        ,  5.        ],
       [ 4.33333333,  3.85714286,  3.5       ],
       [ 3.22222222,  3.        ,  2.81818182],
       [ 2.66666667,  2.53846154,  2.42857143],
       [ 2.33333333,  2.25      ,  2.17647059]])

In [9]:

b = b.reshape(3,6) 
# a@b             #matrix mul
#or
# a.dot(b)
res = np.dot(a,b)
print(res)

[[  90   93   96   99  102  105]
 [ 324  336  348  360  372  384]
 [ 558  579  600  621  642  663]
 [ 792  822  852  882  912  942]
 [1026 1065 1104 1143 1182 1221]
 [1260 1308 1356 1404 1452 1500]]


In [10]:
a.min()


np.int64(0)

In [11]:
b.max()

np.int64(37)

In [12]:
a.argmax()          # gives the maximum index of the array

np.int64(17)

In [13]:
np.sum(a)       #sum all ele in a 

np.int64(153)

In [14]:
np.sum(b, axis = 1)     #sum of each row

array([135, 171, 207])

In [15]:
np.sum(b, axis=0)       #sum of col

array([78, 81, 84, 87, 90, 93])

In [16]:
np.mean(a)

np.float64(8.5)

In [17]:
np.sqrt(a)

array([[0.        , 1.        , 1.41421356],
       [1.73205081, 2.        , 2.23606798],
       [2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479],
       [3.46410162, 3.60555128, 3.74165739],
       [3.87298335, 4.        , 4.12310563]])

In [18]:
np.std(a)   #standard devitaion

np.float64(5.188127472091127)

In [19]:
np.log(b)

array([[2.99573227, 3.04452244, 3.09104245, 3.13549422, 3.17805383,
        3.21887582],
       [3.25809654, 3.29583687, 3.33220451, 3.36729583, 3.40119738,
        3.4339872 ],
       [3.4657359 , 3.49650756, 3.52636052, 3.55534806, 3.58351894,
        3.61091791]])